# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.user import user_pb2 as proto_dot_user_dot_user__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/user/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """User service definition for internal microservice communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/user.v1.UserService/CreateUser',
                request_serializer=proto_dot_user_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=proto_dot_user_dot_user__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/user.v1.UserService/GetUser',
                request_serializer=proto_dot_user_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=proto_dot_user_dot_user__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.GetUserByEmail = channel.unary_unary(
                '/user.v1.UserService/GetUserByEmail',
                request_serializer=proto_dot_user_dot_user__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=proto_dot_user_dot_user__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/user.v1.UserService/UpdateUser',
                request_serializer=proto_dot_user_dot_user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=proto_dot_user_dot_user__pb2.UpdateUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/user.v1.UserService/DeleteUser',
                request_serializer=proto_dot_user_dot_user__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=proto_dot_user_dot_user__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.ValidateUser = channel.unary_unary(
                '/user.v1.UserService/ValidateUser',
                request_serializer=proto_dot_user_dot_user__pb2.ValidateUserRequest.SerializeToString,
                response_deserializer=proto_dot_user_dot_user__pb2.ValidateUserResponse.FromString,
                _registered_method=True)
        self.GetUsers = channel.unary_unary(
                '/user.v1.UserService/GetUsers',
                request_serializer=proto_dot_user_dot_user__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=proto_dot_user_dot_user__pb2.GetUsersResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """User service definition for internal microservice communication
    """

    def CreateUser(self, request, context):
        """Create a new user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Get user by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByEmail(self, request, context):
        """Get user by email
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Update user information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Delete user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateUser(self, request, context):
        """Validate user credentials (for authentication)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """Get multiple users by IDs (batch operation)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=proto_dot_user_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=proto_dot_user_dot_user__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=proto_dot_user_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=proto_dot_user_dot_user__pb2.GetUserResponse.SerializeToString,
            ),
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=proto_dot_user_dot_user__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=proto_dot_user_dot_user__pb2.GetUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=proto_dot_user_dot_user__pb2.UpdateUserRequest.FromString,
                    response_serializer=proto_dot_user_dot_user__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=proto_dot_user_dot_user__pb2.DeleteUserRequest.FromString,
                    response_serializer=proto_dot_user_dot_user__pb2.DeleteUserResponse.SerializeToString,
            ),
            'ValidateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateUser,
                    request_deserializer=proto_dot_user_dot_user__pb2.ValidateUserRequest.FromString,
                    response_serializer=proto_dot_user_dot_user__pb2.ValidateUserResponse.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=proto_dot_user_dot_user__pb2.GetUsersRequest.FromString,
                    response_serializer=proto_dot_user_dot_user__pb2.GetUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User service definition for internal microservice communication
    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/CreateUser',
            proto_dot_user_dot_user__pb2.CreateUserRequest.SerializeToString,
            proto_dot_user_dot_user__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/GetUser',
            proto_dot_user_dot_user__pb2.GetUserRequest.SerializeToString,
            proto_dot_user_dot_user__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/GetUserByEmail',
            proto_dot_user_dot_user__pb2.GetUserByEmailRequest.SerializeToString,
            proto_dot_user_dot_user__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/UpdateUser',
            proto_dot_user_dot_user__pb2.UpdateUserRequest.SerializeToString,
            proto_dot_user_dot_user__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/DeleteUser',
            proto_dot_user_dot_user__pb2.DeleteUserRequest.SerializeToString,
            proto_dot_user_dot_user__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/ValidateUser',
            proto_dot_user_dot_user__pb2.ValidateUserRequest.SerializeToString,
            proto_dot_user_dot_user__pb2.ValidateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/GetUsers',
            proto_dot_user_dot_user__pb2.GetUsersRequest.SerializeToString,
            proto_dot_user_dot_user__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
