// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/payment/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment status enum
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PROCESSING  PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_CANCELLED   PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 6
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PROCESSING",
		3: "PAYMENT_STATUS_COMPLETED",
		4: "PAYMENT_STATUS_FAILED",
		5: "PAYMENT_STATUS_CANCELLED",
		6: "PAYMENT_STATUS_REFUNDED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PROCESSING":  2,
		"PAYMENT_STATUS_COMPLETED":   3,
		"PAYMENT_STATUS_FAILED":      4,
		"PAYMENT_STATUS_CANCELLED":   5,
		"PAYMENT_STATUS_REFUNDED":    6,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_proto_payment_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

// Payment method enum
type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED    PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD    PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_DEBIT_CARD     PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_BANK_TRANSFER  PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_DIGITAL_WALLET PaymentMethod = 4
	PaymentMethod_PAYMENT_METHOD_CRYPTO         PaymentMethod = 5
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_CREDIT_CARD",
		2: "PAYMENT_METHOD_DEBIT_CARD",
		3: "PAYMENT_METHOD_BANK_TRANSFER",
		4: "PAYMENT_METHOD_DIGITAL_WALLET",
		5: "PAYMENT_METHOD_CRYPTO",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED":    0,
		"PAYMENT_METHOD_CREDIT_CARD":    1,
		"PAYMENT_METHOD_DEBIT_CARD":     2,
		"PAYMENT_METHOD_BANK_TRANSFER":  3,
		"PAYMENT_METHOD_DIGITAL_WALLET": 4,
		"PAYMENT_METHOD_CRYPTO":         5,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_proto_payment_payment_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

// Payment entity
type Payment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId               string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId                string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount                float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency              string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod         PaymentMethod          `protobuf:"varint,6,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.v1.PaymentMethod" json:"payment_method,omitempty"`
	Status                PaymentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=payment.v1.PaymentStatus" json:"status,omitempty"`
	ProviderTransactionId string                 `protobuf:"bytes,8,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"`
	CreatedAt             int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`              // Unix timestamp
	UpdatedAt             int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`             // Unix timestamp
	CompletedAt           *int64                 `protobuf:"varint,11,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"` // Unix timestamp
	FailureReason         *string                `protobuf:"bytes,12,opt,name=failure_reason,json=failureReason,proto3,oneof" json:"failure_reason,omitempty"`
	RefundAmount          *float64               `protobuf:"fixed64,13,opt,name=refund_amount,json=refundAmount,proto3,oneof" json:"refund_amount,omitempty"`
	Metadata              map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional payment data
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Payment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Payment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Payment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Payment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *Payment) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *Payment) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Payment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Payment) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

func (x *Payment) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

func (x *Payment) GetRefundAmount() float64 {
	if x != nil && x.RefundAmount != nil {
		return *x.RefundAmount
	}
	return 0
}

func (x *Payment) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Payment provider entity
type PaymentProvider struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SupportedMethods    []PaymentMethod        `protobuf:"varint,3,rep,packed,name=supported_methods,json=supportedMethods,proto3,enum=payment.v1.PaymentMethod" json:"supported_methods,omitempty"`
	SupportedCurrencies []string               `protobuf:"bytes,4,rep,name=supported_currencies,json=supportedCurrencies,proto3" json:"supported_currencies,omitempty"`
	IsActive            bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ApiEndpoint         string                 `protobuf:"bytes,6,opt,name=api_endpoint,json=apiEndpoint,proto3" json:"api_endpoint,omitempty"`
	FeePercentage       float64                `protobuf:"fixed64,7,opt,name=fee_percentage,json=feePercentage,proto3" json:"fee_percentage,omitempty"`
	Configuration       map[string]string      `protobuf:"bytes,8,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Provider-specific config
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PaymentProvider) Reset() {
	*x = PaymentProvider{}
	mi := &file_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentProvider) ProtoMessage() {}

func (x *PaymentProvider) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentProvider.ProtoReflect.Descriptor instead.
func (*PaymentProvider) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentProvider) GetSupportedMethods() []PaymentMethod {
	if x != nil {
		return x.SupportedMethods
	}
	return nil
}

func (x *PaymentProvider) GetSupportedCurrencies() []string {
	if x != nil {
		return x.SupportedCurrencies
	}
	return nil
}

func (x *PaymentProvider) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *PaymentProvider) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *PaymentProvider) GetFeePercentage() float64 {
	if x != nil {
		return x.FeePercentage
	}
	return 0
}

func (x *PaymentProvider) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

// Pagination
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Request messages
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,5,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.v1.PaymentMethod" json:"payment_method,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *CreatePaymentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	Status        *PaymentStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=payment.v1.PaymentStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPaymentsRequest) Reset() {
	*x = GetUserPaymentsRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPaymentsRequest) ProtoMessage() {}

func (x *GetUserPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserPaymentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPaymentsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetUserPaymentsRequest) GetStatus() PaymentStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

type GetOrderPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderPaymentsRequest) Reset() {
	*x = GetOrderPaymentsRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPaymentsRequest) ProtoMessage() {}

func (x *GetOrderPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderPaymentsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ProcessPaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PaymentId      string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ProviderId     string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	PaymentDetails map[string]string      `protobuf:"bytes,3,rep,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Card info, wallet details, etc.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProcessPaymentRequest) GetPaymentDetails() map[string]string {
	if x != nil {
		return x.PaymentDetails
	}
	return nil
}

type ConfirmPaymentRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PaymentId             string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ProviderTransactionId string                 `protobuf:"bytes,2,opt,name=provider_transaction_id,json=providerTransactionId,proto3" json:"provider_transaction_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConfirmPaymentRequest) Reset() {
	*x = ConfirmPaymentRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentRequest) ProtoMessage() {}

func (x *ConfirmPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *ConfirmPaymentRequest) GetProviderTransactionId() string {
	if x != nil {
		return x.ProviderTransactionId
	}
	return ""
}

type CancelPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Reason        *string                `protobuf:"bytes,2,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentRequest) Reset() {
	*x = CancelPaymentRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentRequest) ProtoMessage() {}

func (x *CancelPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentRequest.ProtoReflect.Descriptor instead.
func (*CancelPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{9}
}

func (x *CancelPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CancelPaymentRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Amount        *float64               `protobuf:"fixed64,2,opt,name=amount,proto3,oneof" json:"amount,omitempty"` // Partial refund amount, if not provided, full refund
	Reason        *string                `protobuf:"bytes,3,opt,name=reason,proto3,oneof" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{10}
}

func (x *RefundPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *RefundPaymentRequest) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *RefundPaymentRequest) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

type UpdatePaymentStatusRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PaymentId             string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status                PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=payment.v1.PaymentStatus" json:"status,omitempty"`
	ProviderTransactionId *string                `protobuf:"bytes,3,opt,name=provider_transaction_id,json=providerTransactionId,proto3,oneof" json:"provider_transaction_id,omitempty"`
	FailureReason         *string                `protobuf:"bytes,4,opt,name=failure_reason,json=failureReason,proto3,oneof" json:"failure_reason,omitempty"`
	ProviderData          map[string]string      `protobuf:"bytes,5,rep,name=provider_data,json=providerData,proto3" json:"provider_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Webhook data from provider
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{11}
}

func (x *UpdatePaymentStatusRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *UpdatePaymentStatusRequest) GetProviderTransactionId() string {
	if x != nil && x.ProviderTransactionId != nil {
		return *x.ProviderTransactionId
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

func (x *UpdatePaymentStatusRequest) GetProviderData() map[string]string {
	if x != nil {
		return x.ProviderData
	}
	return nil
}

type ValidatePaymentProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,2,opt,name=payment_method,json=paymentMethod,proto3,enum=payment.v1.PaymentMethod" json:"payment_method,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentProviderRequest) Reset() {
	*x = ValidatePaymentProviderRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentProviderRequest) ProtoMessage() {}

func (x *ValidatePaymentProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentProviderRequest.ProtoReflect.Descriptor instead.
func (*ValidatePaymentProviderRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{12}
}

func (x *ValidatePaymentProviderRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ValidatePaymentProviderRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *ValidatePaymentProviderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Response messages
type CreatePaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreatePaymentResponse_Payment
	//	*CreatePaymentResponse_Error
	Result        isCreatePaymentResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePaymentResponse) GetResult() isCreatePaymentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.Result.(*CreatePaymentResponse_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *CreatePaymentResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*CreatePaymentResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreatePaymentResponse_Result interface {
	isCreatePaymentResponse_Result()
}

type CreatePaymentResponse_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type CreatePaymentResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreatePaymentResponse_Payment) isCreatePaymentResponse_Result() {}

func (*CreatePaymentResponse_Error) isCreatePaymentResponse_Result() {}

type GetPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetPaymentResponse_Payment
	//	*GetPaymentResponse_Error
	Result        isGetPaymentResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{14}
}

func (x *GetPaymentResponse) GetResult() isGetPaymentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.Result.(*GetPaymentResponse_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *GetPaymentResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetPaymentResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetPaymentResponse_Result interface {
	isGetPaymentResponse_Result()
}

type GetPaymentResponse_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type GetPaymentResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetPaymentResponse_Payment) isGetPaymentResponse_Result() {}

func (*GetPaymentResponse_Error) isGetPaymentResponse_Result() {}

type GetUserPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPaymentsResponse) Reset() {
	*x = GetUserPaymentsResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPaymentsResponse) ProtoMessage() {}

func (x *GetUserPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetUserPaymentsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetUserPaymentsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetOrderPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderPaymentsResponse) Reset() {
	*x = GetOrderPaymentsResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderPaymentsResponse) ProtoMessage() {}

func (x *GetOrderPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{16}
}

func (x *GetOrderPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetOrderPaymentsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ProcessPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ProcessPaymentResponse_Payment
	//	*ProcessPaymentResponse_Error
	Result            isProcessPaymentResponse_Result `protobuf_oneof:"result"`
	RedirectUrl       *string                         `protobuf:"bytes,3,opt,name=redirect_url,json=redirectUrl,proto3,oneof" json:"redirect_url,omitempty"` // For 3D Secure or external redirect
	ProviderReference *string                         `protobuf:"bytes,4,opt,name=provider_reference,json=providerReference,proto3,oneof" json:"provider_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessPaymentResponse) GetResult() isProcessPaymentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProcessPaymentResponse) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.Result.(*ProcessPaymentResponse_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *ProcessPaymentResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*ProcessPaymentResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ProcessPaymentResponse) GetRedirectUrl() string {
	if x != nil && x.RedirectUrl != nil {
		return *x.RedirectUrl
	}
	return ""
}

func (x *ProcessPaymentResponse) GetProviderReference() string {
	if x != nil && x.ProviderReference != nil {
		return *x.ProviderReference
	}
	return ""
}

type isProcessPaymentResponse_Result interface {
	isProcessPaymentResponse_Result()
}

type ProcessPaymentResponse_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type ProcessPaymentResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ProcessPaymentResponse_Payment) isProcessPaymentResponse_Result() {}

func (*ProcessPaymentResponse_Error) isProcessPaymentResponse_Result() {}

type ConfirmPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ConfirmPaymentResponse_Payment
	//	*ConfirmPaymentResponse_Error
	Result        isConfirmPaymentResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPaymentResponse) Reset() {
	*x = ConfirmPaymentResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPaymentResponse) ProtoMessage() {}

func (x *ConfirmPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPaymentResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{18}
}

func (x *ConfirmPaymentResponse) GetResult() isConfirmPaymentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ConfirmPaymentResponse) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.Result.(*ConfirmPaymentResponse_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *ConfirmPaymentResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*ConfirmPaymentResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isConfirmPaymentResponse_Result interface {
	isConfirmPaymentResponse_Result()
}

type ConfirmPaymentResponse_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type ConfirmPaymentResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ConfirmPaymentResponse_Payment) isConfirmPaymentResponse_Result() {}

func (*ConfirmPaymentResponse_Error) isConfirmPaymentResponse_Result() {}

type CancelPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CancelPaymentResponse_Payment
	//	*CancelPaymentResponse_Error
	Result        isCancelPaymentResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPaymentResponse) Reset() {
	*x = CancelPaymentResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPaymentResponse) ProtoMessage() {}

func (x *CancelPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPaymentResponse.ProtoReflect.Descriptor instead.
func (*CancelPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{19}
}

func (x *CancelPaymentResponse) GetResult() isCancelPaymentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CancelPaymentResponse) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.Result.(*CancelPaymentResponse_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *CancelPaymentResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*CancelPaymentResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCancelPaymentResponse_Result interface {
	isCancelPaymentResponse_Result()
}

type CancelPaymentResponse_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type CancelPaymentResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CancelPaymentResponse_Payment) isCancelPaymentResponse_Result() {}

func (*CancelPaymentResponse_Error) isCancelPaymentResponse_Result() {}

type RefundPaymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*RefundPaymentResponse_Payment
	//	*RefundPaymentResponse_Error
	Result          isRefundPaymentResponse_Result `protobuf_oneof:"result"`
	RefundReference *string                        `protobuf:"bytes,3,opt,name=refund_reference,json=refundReference,proto3,oneof" json:"refund_reference,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RefundPaymentResponse) Reset() {
	*x = RefundPaymentResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentResponse) ProtoMessage() {}

func (x *RefundPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentResponse.ProtoReflect.Descriptor instead.
func (*RefundPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{20}
}

func (x *RefundPaymentResponse) GetResult() isRefundPaymentResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RefundPaymentResponse) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.Result.(*RefundPaymentResponse_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *RefundPaymentResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*RefundPaymentResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *RefundPaymentResponse) GetRefundReference() string {
	if x != nil && x.RefundReference != nil {
		return *x.RefundReference
	}
	return ""
}

type isRefundPaymentResponse_Result interface {
	isRefundPaymentResponse_Result()
}

type RefundPaymentResponse_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type RefundPaymentResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RefundPaymentResponse_Payment) isRefundPaymentResponse_Result() {}

func (*RefundPaymentResponse_Error) isRefundPaymentResponse_Result() {}

type UpdatePaymentStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdatePaymentStatusResponse_Payment
	//	*UpdatePaymentStatusResponse_Error
	Result        isUpdatePaymentStatusResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusResponse) Reset() {
	*x = UpdatePaymentStatusResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusResponse) ProtoMessage() {}

func (x *UpdatePaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{21}
}

func (x *UpdatePaymentStatusResponse) GetResult() isUpdatePaymentStatusResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdatePaymentStatusResponse) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.Result.(*UpdatePaymentStatusResponse_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *UpdatePaymentStatusResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*UpdatePaymentStatusResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdatePaymentStatusResponse_Result interface {
	isUpdatePaymentStatusResponse_Result()
}

type UpdatePaymentStatusResponse_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type UpdatePaymentStatusResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UpdatePaymentStatusResponse_Payment) isUpdatePaymentStatusResponse_Result() {}

func (*UpdatePaymentStatusResponse_Error) isUpdatePaymentStatusResponse_Result() {}

type ValidatePaymentProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Provider      *PaymentProvider       `protobuf:"bytes,2,opt,name=provider,proto3,oneof" json:"provider,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentProviderResponse) Reset() {
	*x = ValidatePaymentProviderResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentProviderResponse) ProtoMessage() {}

func (x *ValidatePaymentProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentProviderResponse.ProtoReflect.Descriptor instead.
func (*ValidatePaymentProviderResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{22}
}

func (x *ValidatePaymentProviderResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidatePaymentProviderResponse) GetProvider() *PaymentProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ValidatePaymentProviderResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Error message
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_payment_payment_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{23}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_payment_payment_proto protoreflect.FileDescriptor

const file_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/payment/payment.proto\x12\n" +
	"payment.v1\"\x9c\x05\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12@\n" +
	"\x0epayment_method\x18\x06 \x01(\x0e2\x19.payment.v1.PaymentMethodR\rpaymentMethod\x121\n" +
	"\x06status\x18\a \x01(\x0e2\x19.payment.v1.PaymentStatusR\x06status\x126\n" +
	"\x17provider_transaction_id\x18\b \x01(\tR\x15providerTransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12&\n" +
	"\fcompleted_at\x18\v \x01(\x03H\x00R\vcompletedAt\x88\x01\x01\x12*\n" +
	"\x0efailure_reason\x18\f \x01(\tH\x01R\rfailureReason\x88\x01\x01\x12(\n" +
	"\rrefund_amount\x18\r \x01(\x01H\x02R\frefundAmount\x88\x01\x01\x12=\n" +
	"\bmetadata\x18\x0e \x03(\v2!.payment.v1.Payment.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_completed_atB\x11\n" +
	"\x0f_failure_reasonB\x10\n" +
	"\x0e_refund_amount\"\xaf\x03\n" +
	"\x0fPaymentProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12F\n" +
	"\x11supported_methods\x18\x03 \x03(\x0e2\x19.payment.v1.PaymentMethodR\x10supportedMethods\x121\n" +
	"\x14supported_currencies\x18\x04 \x03(\tR\x13supportedCurrencies\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12!\n" +
	"\fapi_endpoint\x18\x06 \x01(\tR\vapiEndpoint\x12%\n" +
	"\x0efee_percentage\x18\a \x01(\x01R\rfeePercentage\x12T\n" +
	"\rconfiguration\x18\b \x03(\v2..payment.v1.PaymentProvider.ConfigurationEntryR\rconfiguration\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"\xc9\x02\n" +
	"\x14CreatePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12@\n" +
	"\x0epayment_method\x18\x05 \x01(\x0e2\x19.payment.v1.PaymentMethodR\rpaymentMethod\x12J\n" +
	"\bmetadata\x18\x06 \x03(\v2..payment.v1.CreatePaymentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11GetPaymentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc0\x01\n" +
	"\x16GetUserPaymentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.payment.v1.PaginationH\x00R\n" +
	"pagination\x88\x01\x01\x126\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.payment.v1.PaymentStatusH\x01R\x06status\x88\x01\x01B\r\n" +
	"\v_paginationB\t\n" +
	"\a_status\"4\n" +
	"\x17GetOrderPaymentsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xfa\x01\n" +
	"\x15ProcessPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12^\n" +
	"\x0fpayment_details\x18\x03 \x03(\v25.payment.v1.ProcessPaymentRequest.PaymentDetailsEntryR\x0epaymentDetails\x1aA\n" +
	"\x13PaymentDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x15ConfirmPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x126\n" +
	"\x17provider_transaction_id\x18\x02 \x01(\tR\x15providerTransactionId\"]\n" +
	"\x14CancelPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1b\n" +
	"\x06reason\x18\x02 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\x85\x01\n" +
	"\x14RefundPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1b\n" +
	"\x06amount\x18\x02 \x01(\x01H\x00R\x06amount\x88\x01\x01\x12\x1b\n" +
	"\x06reason\x18\x03 \x01(\tH\x01R\x06reason\x88\x01\x01B\t\n" +
	"\a_amountB\t\n" +
	"\a_reason\"\xa6\x03\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.payment.v1.PaymentStatusR\x06status\x12;\n" +
	"\x17provider_transaction_id\x18\x03 \x01(\tH\x00R\x15providerTransactionId\x88\x01\x01\x12*\n" +
	"\x0efailure_reason\x18\x04 \x01(\tH\x01R\rfailureReason\x88\x01\x01\x12]\n" +
	"\rprovider_data\x18\x05 \x03(\v28.payment.v1.UpdatePaymentStatusRequest.ProviderDataEntryR\fproviderData\x1a?\n" +
	"\x11ProviderDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x1a\n" +
	"\x18_provider_transaction_idB\x11\n" +
	"\x0f_failure_reason\"\x9f\x01\n" +
	"\x1eValidatePaymentProviderRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12@\n" +
	"\x0epayment_method\x18\x02 \x01(\x0e2\x19.payment.v1.PaymentMethodR\rpaymentMethod\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"}\n" +
	"\x15CreatePaymentResponse\x12/\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentH\x00R\apayment\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.payment.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"z\n" +
	"\x12GetPaymentResponse\x12/\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentH\x00R\apayment\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.payment.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xce\x01\n" +
	"\x17GetUserPaymentsResponse\x12/\n" +
	"\bpayments\x18\x01 \x03(\v2\x13.payment.v1.PaymentR\bpayments\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.payment.v1.PaginationH\x00R\n" +
	"pagination\x88\x01\x01\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x11.payment.v1.ErrorH\x01R\x05error\x88\x01\x01B\r\n" +
	"\v_paginationB\b\n" +
	"\x06_error\"\x83\x01\n" +
	"\x18GetOrderPaymentsResponse\x12/\n" +
	"\bpayments\x18\x01 \x03(\v2\x13.payment.v1.PaymentR\bpayments\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x11.payment.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x82\x02\n" +
	"\x16ProcessPaymentResponse\x12/\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentH\x00R\apayment\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.payment.v1.ErrorH\x00R\x05error\x12&\n" +
	"\fredirect_url\x18\x03 \x01(\tH\x01R\vredirectUrl\x88\x01\x01\x122\n" +
	"\x12provider_reference\x18\x04 \x01(\tH\x02R\x11providerReference\x88\x01\x01B\b\n" +
	"\x06resultB\x0f\n" +
	"\r_redirect_urlB\x15\n" +
	"\x13_provider_reference\"~\n" +
	"\x16ConfirmPaymentResponse\x12/\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentH\x00R\apayment\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.payment.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"}\n" +
	"\x15CancelPaymentResponse\x12/\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentH\x00R\apayment\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.payment.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xc2\x01\n" +
	"\x15RefundPaymentResponse\x12/\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentH\x00R\apayment\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.payment.v1.ErrorH\x00R\x05error\x12.\n" +
	"\x10refund_reference\x18\x03 \x01(\tH\x01R\x0frefundReference\x88\x01\x01B\b\n" +
	"\x06resultB\x13\n" +
	"\x11_refund_reference\"\x83\x01\n" +
	"\x1bUpdatePaymentStatusResponse\x12/\n" +
	"\apayment\x18\x01 \x01(\v2\x13.payment.v1.PaymentH\x00R\apayment\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.payment.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xbf\x01\n" +
	"\x1fValidatePaymentProviderResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12<\n" +
	"\bprovider\x18\x02 \x01(\v2\x1b.payment.v1.PaymentProviderH\x00R\bprovider\x88\x01\x01\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x11.payment.v1.ErrorH\x01R\x05error\x88\x01\x01B\v\n" +
	"\t_providerB\b\n" +
	"\x06_error\"\xab\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\adetails\x18\x03 \x03(\v2\x1e.payment.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xde\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_STATUS_PROCESSING\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18PAYMENT_STATUS_CANCELLED\x10\x05\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x06*\xce\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x01\x12\x1d\n" +
	"\x19PAYMENT_METHOD_DEBIT_CARD\x10\x02\x12 \n" +
	"\x1cPAYMENT_METHOD_BANK_TRANSFER\x10\x03\x12!\n" +
	"\x1dPAYMENT_METHOD_DIGITAL_WALLET\x10\x04\x12\x19\n" +
	"\x15PAYMENT_METHOD_CRYPTO\x10\x052\xa8\a\n" +
	"\x0ePaymentService\x12T\n" +
	"\rCreatePayment\x12 .payment.v1.CreatePaymentRequest\x1a!.payment.v1.CreatePaymentResponse\x12K\n" +
	"\n" +
	"GetPayment\x12\x1d.payment.v1.GetPaymentRequest\x1a\x1e.payment.v1.GetPaymentResponse\x12Z\n" +
	"\x0fGetUserPayments\x12\".payment.v1.GetUserPaymentsRequest\x1a#.payment.v1.GetUserPaymentsResponse\x12]\n" +
	"\x10GetOrderPayments\x12#.payment.v1.GetOrderPaymentsRequest\x1a$.payment.v1.GetOrderPaymentsResponse\x12W\n" +
	"\x0eProcessPayment\x12!.payment.v1.ProcessPaymentRequest\x1a\".payment.v1.ProcessPaymentResponse\x12W\n" +
	"\x0eConfirmPayment\x12!.payment.v1.ConfirmPaymentRequest\x1a\".payment.v1.ConfirmPaymentResponse\x12T\n" +
	"\rCancelPayment\x12 .payment.v1.CancelPaymentRequest\x1a!.payment.v1.CancelPaymentResponse\x12T\n" +
	"\rRefundPayment\x12 .payment.v1.RefundPaymentRequest\x1a!.payment.v1.RefundPaymentResponse\x12f\n" +
	"\x13UpdatePaymentStatus\x12&.payment.v1.UpdatePaymentStatusRequest\x1a'.payment.v1.UpdatePaymentStatusResponse\x12r\n" +
	"\x17ValidatePaymentProvider\x12*.payment.v1.ValidatePaymentProviderRequest\x1a+.payment.v1.ValidatePaymentProviderResponseBa\n" +
	"\x1acom.marketplace.payment.v1Z$user-service/proto/payment;paymentpb\xaa\x02\x1cProductService.Proto.Paymentb\x06proto3"

var (
	file_proto_payment_payment_proto_rawDescOnce sync.Once
	file_proto_payment_payment_proto_rawDescData []byte
)

func file_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_payment_proto_rawDesc), len(file_proto_payment_payment_proto_rawDesc)))
	})
	return file_proto_payment_payment_proto_rawDescData
}

var file_proto_payment_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_payment_payment_proto_goTypes = []any{
	(PaymentStatus)(0),                      // 0: payment.v1.PaymentStatus
	(PaymentMethod)(0),                      // 1: payment.v1.PaymentMethod
	(*Payment)(nil),                         // 2: payment.v1.Payment
	(*PaymentProvider)(nil),                 // 3: payment.v1.PaymentProvider
	(*Pagination)(nil),                      // 4: payment.v1.Pagination
	(*CreatePaymentRequest)(nil),            // 5: payment.v1.CreatePaymentRequest
	(*GetPaymentRequest)(nil),               // 6: payment.v1.GetPaymentRequest
	(*GetUserPaymentsRequest)(nil),          // 7: payment.v1.GetUserPaymentsRequest
	(*GetOrderPaymentsRequest)(nil),         // 8: payment.v1.GetOrderPaymentsRequest
	(*ProcessPaymentRequest)(nil),           // 9: payment.v1.ProcessPaymentRequest
	(*ConfirmPaymentRequest)(nil),           // 10: payment.v1.ConfirmPaymentRequest
	(*CancelPaymentRequest)(nil),            // 11: payment.v1.CancelPaymentRequest
	(*RefundPaymentRequest)(nil),            // 12: payment.v1.RefundPaymentRequest
	(*UpdatePaymentStatusRequest)(nil),      // 13: payment.v1.UpdatePaymentStatusRequest
	(*ValidatePaymentProviderRequest)(nil),  // 14: payment.v1.ValidatePaymentProviderRequest
	(*CreatePaymentResponse)(nil),           // 15: payment.v1.CreatePaymentResponse
	(*GetPaymentResponse)(nil),              // 16: payment.v1.GetPaymentResponse
	(*GetUserPaymentsResponse)(nil),         // 17: payment.v1.GetUserPaymentsResponse
	(*GetOrderPaymentsResponse)(nil),        // 18: payment.v1.GetOrderPaymentsResponse
	(*ProcessPaymentResponse)(nil),          // 19: payment.v1.ProcessPaymentResponse
	(*ConfirmPaymentResponse)(nil),          // 20: payment.v1.ConfirmPaymentResponse
	(*CancelPaymentResponse)(nil),           // 21: payment.v1.CancelPaymentResponse
	(*RefundPaymentResponse)(nil),           // 22: payment.v1.RefundPaymentResponse
	(*UpdatePaymentStatusResponse)(nil),     // 23: payment.v1.UpdatePaymentStatusResponse
	(*ValidatePaymentProviderResponse)(nil), // 24: payment.v1.ValidatePaymentProviderResponse
	(*Error)(nil),                           // 25: payment.v1.Error
	nil,                                     // 26: payment.v1.Payment.MetadataEntry
	nil,                                     // 27: payment.v1.PaymentProvider.ConfigurationEntry
	nil,                                     // 28: payment.v1.CreatePaymentRequest.MetadataEntry
	nil,                                     // 29: payment.v1.ProcessPaymentRequest.PaymentDetailsEntry
	nil,                                     // 30: payment.v1.UpdatePaymentStatusRequest.ProviderDataEntry
	nil,                                     // 31: payment.v1.Error.DetailsEntry
}
var file_proto_payment_payment_proto_depIdxs = []int32{
	1,  // 0: payment.v1.Payment.payment_method:type_name -> payment.v1.PaymentMethod
	0,  // 1: payment.v1.Payment.status:type_name -> payment.v1.PaymentStatus
	26, // 2: payment.v1.Payment.metadata:type_name -> payment.v1.Payment.MetadataEntry
	1,  // 3: payment.v1.PaymentProvider.supported_methods:type_name -> payment.v1.PaymentMethod
	27, // 4: payment.v1.PaymentProvider.configuration:type_name -> payment.v1.PaymentProvider.ConfigurationEntry
	1,  // 5: payment.v1.CreatePaymentRequest.payment_method:type_name -> payment.v1.PaymentMethod
	28, // 6: payment.v1.CreatePaymentRequest.metadata:type_name -> payment.v1.CreatePaymentRequest.MetadataEntry
	4,  // 7: payment.v1.GetUserPaymentsRequest.pagination:type_name -> payment.v1.Pagination
	0,  // 8: payment.v1.GetUserPaymentsRequest.status:type_name -> payment.v1.PaymentStatus
	29, // 9: payment.v1.ProcessPaymentRequest.payment_details:type_name -> payment.v1.ProcessPaymentRequest.PaymentDetailsEntry
	0,  // 10: payment.v1.UpdatePaymentStatusRequest.status:type_name -> payment.v1.PaymentStatus
	30, // 11: payment.v1.UpdatePaymentStatusRequest.provider_data:type_name -> payment.v1.UpdatePaymentStatusRequest.ProviderDataEntry
	1,  // 12: payment.v1.ValidatePaymentProviderRequest.payment_method:type_name -> payment.v1.PaymentMethod
	2,  // 13: payment.v1.CreatePaymentResponse.payment:type_name -> payment.v1.Payment
	25, // 14: payment.v1.CreatePaymentResponse.error:type_name -> payment.v1.Error
	2,  // 15: payment.v1.GetPaymentResponse.payment:type_name -> payment.v1.Payment
	25, // 16: payment.v1.GetPaymentResponse.error:type_name -> payment.v1.Error
	2,  // 17: payment.v1.GetUserPaymentsResponse.payments:type_name -> payment.v1.Payment
	4,  // 18: payment.v1.GetUserPaymentsResponse.pagination:type_name -> payment.v1.Pagination
	25, // 19: payment.v1.GetUserPaymentsResponse.error:type_name -> payment.v1.Error
	2,  // 20: payment.v1.GetOrderPaymentsResponse.payments:type_name -> payment.v1.Payment
	25, // 21: payment.v1.GetOrderPaymentsResponse.error:type_name -> payment.v1.Error
	2,  // 22: payment.v1.ProcessPaymentResponse.payment:type_name -> payment.v1.Payment
	25, // 23: payment.v1.ProcessPaymentResponse.error:type_name -> payment.v1.Error
	2,  // 24: payment.v1.ConfirmPaymentResponse.payment:type_name -> payment.v1.Payment
	25, // 25: payment.v1.ConfirmPaymentResponse.error:type_name -> payment.v1.Error
	2,  // 26: payment.v1.CancelPaymentResponse.payment:type_name -> payment.v1.Payment
	25, // 27: payment.v1.CancelPaymentResponse.error:type_name -> payment.v1.Error
	2,  // 28: payment.v1.RefundPaymentResponse.payment:type_name -> payment.v1.Payment
	25, // 29: payment.v1.RefundPaymentResponse.error:type_name -> payment.v1.Error
	2,  // 30: payment.v1.UpdatePaymentStatusResponse.payment:type_name -> payment.v1.Payment
	25, // 31: payment.v1.UpdatePaymentStatusResponse.error:type_name -> payment.v1.Error
	3,  // 32: payment.v1.ValidatePaymentProviderResponse.provider:type_name -> payment.v1.PaymentProvider
	25, // 33: payment.v1.ValidatePaymentProviderResponse.error:type_name -> payment.v1.Error
	31, // 34: payment.v1.Error.details:type_name -> payment.v1.Error.DetailsEntry
	5,  // 35: payment.v1.PaymentService.CreatePayment:input_type -> payment.v1.CreatePaymentRequest
	6,  // 36: payment.v1.PaymentService.GetPayment:input_type -> payment.v1.GetPaymentRequest
	7,  // 37: payment.v1.PaymentService.GetUserPayments:input_type -> payment.v1.GetUserPaymentsRequest
	8,  // 38: payment.v1.PaymentService.GetOrderPayments:input_type -> payment.v1.GetOrderPaymentsRequest
	9,  // 39: payment.v1.PaymentService.ProcessPayment:input_type -> payment.v1.ProcessPaymentRequest
	10, // 40: payment.v1.PaymentService.ConfirmPayment:input_type -> payment.v1.ConfirmPaymentRequest
	11, // 41: payment.v1.PaymentService.CancelPayment:input_type -> payment.v1.CancelPaymentRequest
	12, // 42: payment.v1.PaymentService.RefundPayment:input_type -> payment.v1.RefundPaymentRequest
	13, // 43: payment.v1.PaymentService.UpdatePaymentStatus:input_type -> payment.v1.UpdatePaymentStatusRequest
	14, // 44: payment.v1.PaymentService.ValidatePaymentProvider:input_type -> payment.v1.ValidatePaymentProviderRequest
	15, // 45: payment.v1.PaymentService.CreatePayment:output_type -> payment.v1.CreatePaymentResponse
	16, // 46: payment.v1.PaymentService.GetPayment:output_type -> payment.v1.GetPaymentResponse
	17, // 47: payment.v1.PaymentService.GetUserPayments:output_type -> payment.v1.GetUserPaymentsResponse
	18, // 48: payment.v1.PaymentService.GetOrderPayments:output_type -> payment.v1.GetOrderPaymentsResponse
	19, // 49: payment.v1.PaymentService.ProcessPayment:output_type -> payment.v1.ProcessPaymentResponse
	20, // 50: payment.v1.PaymentService.ConfirmPayment:output_type -> payment.v1.ConfirmPaymentResponse
	21, // 51: payment.v1.PaymentService.CancelPayment:output_type -> payment.v1.CancelPaymentResponse
	22, // 52: payment.v1.PaymentService.RefundPayment:output_type -> payment.v1.RefundPaymentResponse
	23, // 53: payment.v1.PaymentService.UpdatePaymentStatus:output_type -> payment.v1.UpdatePaymentStatusResponse
	24, // 54: payment.v1.PaymentService.ValidatePaymentProvider:output_type -> payment.v1.ValidatePaymentProviderResponse
	45, // [45:55] is the sub-list for method output_type
	35, // [35:45] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_proto_payment_payment_proto_init() }
func file_proto_payment_payment_proto_init() {
	if File_proto_payment_payment_proto != nil {
		return
	}
	file_proto_payment_payment_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_payment_payment_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_payment_payment_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_payment_payment_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_payment_payment_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_payment_payment_proto_msgTypes[13].OneofWrappers = []any{
		(*CreatePaymentResponse_Payment)(nil),
		(*CreatePaymentResponse_Error)(nil),
	}
	file_proto_payment_payment_proto_msgTypes[14].OneofWrappers = []any{
		(*GetPaymentResponse_Payment)(nil),
		(*GetPaymentResponse_Error)(nil),
	}
	file_proto_payment_payment_proto_msgTypes[15].OneofWrappers = []any{}
	file_proto_payment_payment_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_payment_payment_proto_msgTypes[17].OneofWrappers = []any{
		(*ProcessPaymentResponse_Payment)(nil),
		(*ProcessPaymentResponse_Error)(nil),
	}
	file_proto_payment_payment_proto_msgTypes[18].OneofWrappers = []any{
		(*ConfirmPaymentResponse_Payment)(nil),
		(*ConfirmPaymentResponse_Error)(nil),
	}
	file_proto_payment_payment_proto_msgTypes[19].OneofWrappers = []any{
		(*CancelPaymentResponse_Payment)(nil),
		(*CancelPaymentResponse_Error)(nil),
	}
	file_proto_payment_payment_proto_msgTypes[20].OneofWrappers = []any{
		(*RefundPaymentResponse_Payment)(nil),
		(*RefundPaymentResponse_Error)(nil),
	}
	file_proto_payment_payment_proto_msgTypes[21].OneofWrappers = []any{
		(*UpdatePaymentStatusResponse_Payment)(nil),
		(*UpdatePaymentStatusResponse_Error)(nil),
	}
	file_proto_payment_payment_proto_msgTypes[22].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_payment_proto_rawDesc), len(file_proto_payment_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_payment_proto_depIdxs,
		EnumInfos:         file_proto_payment_payment_proto_enumTypes,
		MessageInfos:      file_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_payment_proto = out.File
	file_proto_payment_payment_proto_goTypes = nil
	file_proto_payment_payment_proto_depIdxs = nil
}
