// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/product/product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Product entity
type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity int32                  `protobuf:"varint,5,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Sku           string                 `protobuf:"bytes,7,opt,name=sku,proto3" json:"sku,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`  // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	Tags          []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional product attributes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_proto_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Product) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Product) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Product) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Product filters
type ProductFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *string                `protobuf:"bytes,1,opt,name=category,proto3,oneof" json:"category,omitempty"`
	MinPrice      *float64               `protobuf:"fixed64,2,opt,name=min_price,json=minPrice,proto3,oneof" json:"min_price,omitempty"`
	MaxPrice      *float64               `protobuf:"fixed64,3,opt,name=max_price,json=maxPrice,proto3,oneof" json:"max_price,omitempty"`
	InStock       *bool                  `protobuf:"varint,4,opt,name=in_stock,json=inStock,proto3,oneof" json:"in_stock,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	IsActive      *bool                  `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductFilters) Reset() {
	*x = ProductFilters{}
	mi := &file_proto_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFilters) ProtoMessage() {}

func (x *ProductFilters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductFilters.ProtoReflect.Descriptor instead.
func (*ProductFilters) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductFilters) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *ProductFilters) GetMinPrice() float64 {
	if x != nil && x.MinPrice != nil {
		return *x.MinPrice
	}
	return 0
}

func (x *ProductFilters) GetMaxPrice() float64 {
	if x != nil && x.MaxPrice != nil {
		return *x.MaxPrice
	}
	return 0
}

func (x *ProductFilters) GetInStock() bool {
	if x != nil && x.InStock != nil {
		return *x.InStock
	}
	return false
}

func (x *ProductFilters) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProductFilters) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

// Pagination
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_proto_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// Product reservation item
type ProductReservationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductReservationItem) Reset() {
	*x = ProductReservationItem{}
	mi := &file_proto_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductReservationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductReservationItem) ProtoMessage() {}

func (x *ProductReservationItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductReservationItem.ProtoReflect.Descriptor instead.
func (*ProductReservationItem) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductReservationItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductReservationItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Request messages
type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	StockQuantity int32                  `protobuf:"varint,4,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetStockQuantity() int32 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateProductRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *ProductFilters        `protobuf:"bytes,1,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_proto_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductsRequest) GetFilters() *ProductFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *GetProductsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Price         *float64               `protobuf:"fixed64,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	StockQuantity *int32                 `protobuf:"varint,5,opt,name=stock_quantity,json=stockQuantity,proto3,oneof" json:"stock_quantity,omitempty"`
	Category      *string                `protobuf:"bytes,6,opt,name=category,proto3,oneof" json:"category,omitempty"`
	Sku           *string                `protobuf:"bytes,7,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	IsActive      *bool                  `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetStockQuantity() int32 {
	if x != nil && x.StockQuantity != nil {
		return *x.StockQuantity
	}
	return 0
}

func (x *UpdateProductRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *UpdateProductRequest) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

func (x *UpdateProductRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateProductRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateProductRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UpdateProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStockRequest) Reset() {
	*x = UpdateProductStockRequest{}
	mi := &file_proto_product_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStockRequest) ProtoMessage() {}

func (x *UpdateProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductStockRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateProductPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriceRequest) Reset() {
	*x = UpdateProductPriceRequest{}
	mi := &file_proto_product_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriceRequest) ProtoMessage() {}

func (x *UpdateProductPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriceRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateProductPriceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductPriceRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_proto_product_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CheckProductAvailabilityRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Items         []*ProductReservationItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductAvailabilityRequest) Reset() {
	*x = CheckProductAvailabilityRequest{}
	mi := &file_proto_product_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductAvailabilityRequest) ProtoMessage() {}

func (x *CheckProductAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckProductAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{11}
}

func (x *CheckProductAvailabilityRequest) GetItems() []*ProductReservationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveProductsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ReservationId string                    `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Items         []*ProductReservationItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ExpiryTime    int64                     `protobuf:"varint,3,opt,name=expiry_time,json=expiryTime,proto3" json:"expiry_time,omitempty"` // Unix timestamp when reservation expires
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductsRequest) Reset() {
	*x = ReserveProductsRequest{}
	mi := &file_proto_product_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductsRequest) ProtoMessage() {}

func (x *ReserveProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductsRequest.ProtoReflect.Descriptor instead.
func (*ReserveProductsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{12}
}

func (x *ReserveProductsRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveProductsRequest) GetItems() []*ProductReservationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveProductsRequest) GetExpiryTime() int64 {
	if x != nil {
		return x.ExpiryTime
	}
	return 0
}

type ConfirmReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_proto_product_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{13}
}

func (x *ConfirmReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type CancelReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationRequest) Reset() {
	*x = CancelReservationRequest{}
	mi := &file_proto_product_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationRequest) ProtoMessage() {}

func (x *CancelReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationRequest.ProtoReflect.Descriptor instead.
func (*CancelReservationRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{14}
}

func (x *CancelReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

// Response messages
type CreateProductResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateProductResponse_Product
	//	*CreateProductResponse_Error
	Result        isCreateProductResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{15}
}

func (x *CreateProductResponse) GetResult() isCreateProductResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		if x, ok := x.Result.(*CreateProductResponse_Product); ok {
			return x.Product
		}
	}
	return nil
}

func (x *CreateProductResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*CreateProductResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateProductResponse_Result interface {
	isCreateProductResponse_Result()
}

type CreateProductResponse_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

type CreateProductResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateProductResponse_Product) isCreateProductResponse_Result() {}

func (*CreateProductResponse_Error) isCreateProductResponse_Result() {}

type GetProductResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetProductResponse_Product
	//	*GetProductResponse_Error
	Result        isGetProductResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{16}
}

func (x *GetProductResponse) GetResult() isGetProductResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		if x, ok := x.Result.(*GetProductResponse_Product); ok {
			return x.Product
		}
	}
	return nil
}

func (x *GetProductResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetProductResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetProductResponse_Result interface {
	isGetProductResponse_Result()
}

type GetProductResponse_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

type GetProductResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetProductResponse_Product) isGetProductResponse_Result() {}

func (*GetProductResponse_Error) isGetProductResponse_Result() {}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3,oneof" json:"pagination,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_proto_product_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{17}
}

func (x *GetProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetProductsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *GetProductsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateProductResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateProductResponse_Product
	//	*UpdateProductResponse_Error
	Result        isUpdateProductResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProductResponse) GetResult() isUpdateProductResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateProductResponse) GetProduct() *Product {
	if x != nil {
		if x, ok := x.Result.(*UpdateProductResponse_Product); ok {
			return x.Product
		}
	}
	return nil
}

func (x *UpdateProductResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*UpdateProductResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateProductResponse_Result interface {
	isUpdateProductResponse_Result()
}

type UpdateProductResponse_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

type UpdateProductResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UpdateProductResponse_Product) isUpdateProductResponse_Result() {}

func (*UpdateProductResponse_Error) isUpdateProductResponse_Result() {}

type UpdateProductStockResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateProductStockResponse_Product
	//	*UpdateProductStockResponse_Error
	Result        isUpdateProductStockResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStockResponse) Reset() {
	*x = UpdateProductStockResponse{}
	mi := &file_proto_product_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStockResponse) ProtoMessage() {}

func (x *UpdateProductStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateProductStockResponse) GetResult() isUpdateProductStockResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateProductStockResponse) GetProduct() *Product {
	if x != nil {
		if x, ok := x.Result.(*UpdateProductStockResponse_Product); ok {
			return x.Product
		}
	}
	return nil
}

func (x *UpdateProductStockResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*UpdateProductStockResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateProductStockResponse_Result interface {
	isUpdateProductStockResponse_Result()
}

type UpdateProductStockResponse_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

type UpdateProductStockResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UpdateProductStockResponse_Product) isUpdateProductStockResponse_Result() {}

func (*UpdateProductStockResponse_Error) isUpdateProductStockResponse_Result() {}

type UpdateProductPriceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateProductPriceResponse_Product
	//	*UpdateProductPriceResponse_Error
	Result        isUpdateProductPriceResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriceResponse) Reset() {
	*x = UpdateProductPriceResponse{}
	mi := &file_proto_product_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriceResponse) ProtoMessage() {}

func (x *UpdateProductPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriceResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateProductPriceResponse) GetResult() isUpdateProductPriceResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateProductPriceResponse) GetProduct() *Product {
	if x != nil {
		if x, ok := x.Result.(*UpdateProductPriceResponse_Product); ok {
			return x.Product
		}
	}
	return nil
}

func (x *UpdateProductPriceResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*UpdateProductPriceResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateProductPriceResponse_Result interface {
	isUpdateProductPriceResponse_Result()
}

type UpdateProductPriceResponse_Product struct {
	Product *Product `protobuf:"bytes,1,opt,name=product,proto3,oneof"`
}

type UpdateProductPriceResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UpdateProductPriceResponse_Product) isUpdateProductPriceResponse_Result() {}

func (*UpdateProductPriceResponse_Error) isUpdateProductPriceResponse_Result() {}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_proto_product_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteProductResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ProductAvailability struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	IsAvailable       bool                   `protobuf:"varint,2,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	AvailableQuantity int32                  `protobuf:"varint,3,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProductAvailability) Reset() {
	*x = ProductAvailability{}
	mi := &file_proto_product_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductAvailability) ProtoMessage() {}

func (x *ProductAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductAvailability.ProtoReflect.Descriptor instead.
func (*ProductAvailability) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{22}
}

func (x *ProductAvailability) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductAvailability) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *ProductAvailability) GetAvailableQuantity() int32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

type CheckProductAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Availability  []*ProductAvailability `protobuf:"bytes,1,rep,name=availability,proto3" json:"availability,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProductAvailabilityResponse) Reset() {
	*x = CheckProductAvailabilityResponse{}
	mi := &file_proto_product_product_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProductAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProductAvailabilityResponse) ProtoMessage() {}

func (x *CheckProductAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProductAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckProductAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{23}
}

func (x *CheckProductAvailabilityResponse) GetAvailability() []*ProductAvailability {
	if x != nil {
		return x.Availability
	}
	return nil
}

func (x *CheckProductAvailabilityResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ReserveProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ReservedItems []*ProductAvailability `protobuf:"bytes,3,rep,name=reserved_items,json=reservedItems,proto3" json:"reserved_items,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveProductsResponse) Reset() {
	*x = ReserveProductsResponse{}
	mi := &file_proto_product_product_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveProductsResponse) ProtoMessage() {}

func (x *ReserveProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveProductsResponse.ProtoReflect.Descriptor instead.
func (*ReserveProductsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{24}
}

func (x *ReserveProductsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveProductsResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveProductsResponse) GetReservedItems() []*ProductAvailability {
	if x != nil {
		return x.ReservedItems
	}
	return nil
}

func (x *ReserveProductsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ConfirmReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationResponse) Reset() {
	*x = ConfirmReservationResponse{}
	mi := &file_proto_product_product_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationResponse) ProtoMessage() {}

func (x *ConfirmReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{25}
}

func (x *ConfirmReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmReservationResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CancelReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *Error                 `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReservationResponse) Reset() {
	*x = CancelReservationResponse{}
	mi := &file_proto_product_product_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReservationResponse) ProtoMessage() {}

func (x *CancelReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReservationResponse.ProtoReflect.Descriptor instead.
func (*CancelReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{26}
}

func (x *CancelReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelReservationResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Error message
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_product_product_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_product_product_proto_rawDescGZIP(), []int{27}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_product_product_proto protoreflect.FileDescriptor

const file_proto_product_product_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/product.proto\x12\n" +
	"product.v1\"\xa5\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x05 \x01(\x05R\rstockQuantity\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x10\n" +
	"\x03sku\x18\a \x01(\tR\x03sku\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12=\n" +
	"\bmetadata\x18\f \x03(\v2!.product.v1.Product.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x02\n" +
	"\x0eProductFilters\x12\x1f\n" +
	"\bcategory\x18\x01 \x01(\tH\x00R\bcategory\x88\x01\x01\x12 \n" +
	"\tmin_price\x18\x02 \x01(\x01H\x01R\bminPrice\x88\x01\x01\x12 \n" +
	"\tmax_price\x18\x03 \x01(\x01H\x02R\bmaxPrice\x88\x01\x01\x12\x1e\n" +
	"\bin_stock\x18\x04 \x01(\bH\x03R\ainStock\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12 \n" +
	"\tis_active\x18\x06 \x01(\bH\x04R\bisActive\x88\x01\x01B\v\n" +
	"\t_categoryB\f\n" +
	"\n" +
	"_min_priceB\f\n" +
	"\n" +
	"_max_priceB\v\n" +
	"\t_in_stockB\f\n" +
	"\n" +
	"_is_active\"m\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"S\n" +
	"\x16ProductReservationItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xd4\x02\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12%\n" +
	"\x0estock_quantity\x18\x04 \x01(\x05R\rstockQuantity\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12J\n" +
	"\bmetadata\x18\b \x03(\v2..product.v1.CreateProductRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa7\x01\n" +
	"\x12GetProductsRequest\x129\n" +
	"\afilters\x18\x01 \x01(\v2\x1a.product.v1.ProductFiltersH\x00R\afilters\x88\x01\x01\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.product.v1.PaginationH\x01R\n" +
	"pagination\x88\x01\x01B\n" +
	"\n" +
	"\b_filtersB\r\n" +
	"\v_pagination\"\xfd\x03\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x04 \x01(\x01H\x02R\x05price\x88\x01\x01\x12*\n" +
	"\x0estock_quantity\x18\x05 \x01(\x05H\x03R\rstockQuantity\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x06 \x01(\tH\x04R\bcategory\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\a \x01(\tH\x05R\x03sku\x88\x01\x01\x12 \n" +
	"\tis_active\x18\b \x01(\bH\x06R\bisActive\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12J\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2..product.v1.UpdateProductRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_priceB\x11\n" +
	"\x0f_stock_quantityB\v\n" +
	"\t_categoryB\x06\n" +
	"\x04_skuB\f\n" +
	"\n" +
	"_is_active\"G\n" +
	"\x19UpdateProductStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"A\n" +
	"\x19UpdateProductPriceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x1fCheckProductAvailabilityRequest\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".product.v1.ProductReservationItemR\x05items\"\x9a\x01\n" +
	"\x16ReserveProductsRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x128\n" +
	"\x05items\x18\x02 \x03(\v2\".product.v1.ProductReservationItemR\x05items\x12\x1f\n" +
	"\vexpiry_time\x18\x03 \x01(\x03R\n" +
	"expiryTime\"B\n" +
	"\x19ConfirmReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"A\n" +
	"\x18CancelReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"}\n" +
	"\x15CreateProductResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductH\x00R\aproduct\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"z\n" +
	"\x12GetProductResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductH\x00R\aproduct\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xca\x01\n" +
	"\x13GetProductsResponse\x12/\n" +
	"\bproducts\x18\x01 \x03(\v2\x13.product.v1.ProductR\bproducts\x12;\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x16.product.v1.PaginationH\x00R\n" +
	"pagination\x88\x01\x01\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x11.product.v1.ErrorH\x01R\x05error\x88\x01\x01B\r\n" +
	"\v_paginationB\b\n" +
	"\x06_error\"}\n" +
	"\x15UpdateProductResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductH\x00R\aproduct\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x82\x01\n" +
	"\x1aUpdateProductStockResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductH\x00R\aproduct\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x82\x01\n" +
	"\x1aUpdateProductPriceResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductH\x00R\aproduct\x12)\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"i\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x86\x01\n" +
	"\x13ProductAvailability\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fis_available\x18\x02 \x01(\bR\visAvailable\x12-\n" +
	"\x12available_quantity\x18\x03 \x01(\x05R\x11availableQuantity\"\x9f\x01\n" +
	" CheckProductAvailabilityResponse\x12C\n" +
	"\favailability\x18\x01 \x03(\v2\x1f.product.v1.ProductAvailabilityR\favailability\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xda\x01\n" +
	"\x17ReserveProductsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12F\n" +
	"\x0ereserved_items\x18\x03 \x03(\v2\x1f.product.v1.ProductAvailabilityR\rreservedItems\x12,\n" +
	"\x05error\x18\x04 \x01(\v2\x11.product.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"n\n" +
	"\x1aConfirmReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"m\n" +
	"\x19CancelReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x05error\x18\x02 \x01(\v2\x11.product.v1.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xab\x01\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\adetails\x18\x03 \x03(\v2\x1e.product.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x93\b\n" +
	"\x0eProductService\x12T\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a!.product.v1.CreateProductResponse\x12K\n" +
	"\n" +
	"GetProduct\x12\x1d.product.v1.GetProductRequest\x1a\x1e.product.v1.GetProductResponse\x12N\n" +
	"\vGetProducts\x12\x1e.product.v1.GetProductsRequest\x1a\x1f.product.v1.GetProductsResponse\x12T\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a!.product.v1.UpdateProductResponse\x12c\n" +
	"\x12UpdateProductStock\x12%.product.v1.UpdateProductStockRequest\x1a&.product.v1.UpdateProductStockResponse\x12c\n" +
	"\x12UpdateProductPrice\x12%.product.v1.UpdateProductPriceRequest\x1a&.product.v1.UpdateProductPriceResponse\x12T\n" +
	"\rDeleteProduct\x12 .product.v1.DeleteProductRequest\x1a!.product.v1.DeleteProductResponse\x12u\n" +
	"\x18CheckProductAvailability\x12+.product.v1.CheckProductAvailabilityRequest\x1a,.product.v1.CheckProductAvailabilityResponse\x12Z\n" +
	"\x0fReserveProducts\x12\".product.v1.ReserveProductsRequest\x1a#.product.v1.ReserveProductsResponse\x12c\n" +
	"\x12ConfirmReservation\x12%.product.v1.ConfirmReservationRequest\x1a&.product.v1.ConfirmReservationResponse\x12`\n" +
	"\x11CancelReservation\x12$.product.v1.CancelReservationRequest\x1a%.product.v1.CancelReservationResponseBa\n" +
	"\x1acom.marketplace.product.v1Z$user-service/proto/product;productpb\xaa\x02\x1cProductService.Proto.Productb\x06proto3"

var (
	file_proto_product_product_proto_rawDescOnce sync.Once
	file_proto_product_product_proto_rawDescData []byte
)

func file_proto_product_product_proto_rawDescGZIP() []byte {
	file_proto_product_product_proto_rawDescOnce.Do(func() {
		file_proto_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)))
	})
	return file_proto_product_product_proto_rawDescData
}

var file_proto_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_product_product_proto_goTypes = []any{
	(*Product)(nil),                          // 0: product.v1.Product
	(*ProductFilters)(nil),                   // 1: product.v1.ProductFilters
	(*Pagination)(nil),                       // 2: product.v1.Pagination
	(*ProductReservationItem)(nil),           // 3: product.v1.ProductReservationItem
	(*CreateProductRequest)(nil),             // 4: product.v1.CreateProductRequest
	(*GetProductRequest)(nil),                // 5: product.v1.GetProductRequest
	(*GetProductsRequest)(nil),               // 6: product.v1.GetProductsRequest
	(*UpdateProductRequest)(nil),             // 7: product.v1.UpdateProductRequest
	(*UpdateProductStockRequest)(nil),        // 8: product.v1.UpdateProductStockRequest
	(*UpdateProductPriceRequest)(nil),        // 9: product.v1.UpdateProductPriceRequest
	(*DeleteProductRequest)(nil),             // 10: product.v1.DeleteProductRequest
	(*CheckProductAvailabilityRequest)(nil),  // 11: product.v1.CheckProductAvailabilityRequest
	(*ReserveProductsRequest)(nil),           // 12: product.v1.ReserveProductsRequest
	(*ConfirmReservationRequest)(nil),        // 13: product.v1.ConfirmReservationRequest
	(*CancelReservationRequest)(nil),         // 14: product.v1.CancelReservationRequest
	(*CreateProductResponse)(nil),            // 15: product.v1.CreateProductResponse
	(*GetProductResponse)(nil),               // 16: product.v1.GetProductResponse
	(*GetProductsResponse)(nil),              // 17: product.v1.GetProductsResponse
	(*UpdateProductResponse)(nil),            // 18: product.v1.UpdateProductResponse
	(*UpdateProductStockResponse)(nil),       // 19: product.v1.UpdateProductStockResponse
	(*UpdateProductPriceResponse)(nil),       // 20: product.v1.UpdateProductPriceResponse
	(*DeleteProductResponse)(nil),            // 21: product.v1.DeleteProductResponse
	(*ProductAvailability)(nil),              // 22: product.v1.ProductAvailability
	(*CheckProductAvailabilityResponse)(nil), // 23: product.v1.CheckProductAvailabilityResponse
	(*ReserveProductsResponse)(nil),          // 24: product.v1.ReserveProductsResponse
	(*ConfirmReservationResponse)(nil),       // 25: product.v1.ConfirmReservationResponse
	(*CancelReservationResponse)(nil),        // 26: product.v1.CancelReservationResponse
	(*Error)(nil),                            // 27: product.v1.Error
	nil,                                      // 28: product.v1.Product.MetadataEntry
	nil,                                      // 29: product.v1.CreateProductRequest.MetadataEntry
	nil,                                      // 30: product.v1.UpdateProductRequest.MetadataEntry
	nil,                                      // 31: product.v1.Error.DetailsEntry
}
var file_proto_product_product_proto_depIdxs = []int32{
	28, // 0: product.v1.Product.metadata:type_name -> product.v1.Product.MetadataEntry
	29, // 1: product.v1.CreateProductRequest.metadata:type_name -> product.v1.CreateProductRequest.MetadataEntry
	1,  // 2: product.v1.GetProductsRequest.filters:type_name -> product.v1.ProductFilters
	2,  // 3: product.v1.GetProductsRequest.pagination:type_name -> product.v1.Pagination
	30, // 4: product.v1.UpdateProductRequest.metadata:type_name -> product.v1.UpdateProductRequest.MetadataEntry
	3,  // 5: product.v1.CheckProductAvailabilityRequest.items:type_name -> product.v1.ProductReservationItem
	3,  // 6: product.v1.ReserveProductsRequest.items:type_name -> product.v1.ProductReservationItem
	0,  // 7: product.v1.CreateProductResponse.product:type_name -> product.v1.Product
	27, // 8: product.v1.CreateProductResponse.error:type_name -> product.v1.Error
	0,  // 9: product.v1.GetProductResponse.product:type_name -> product.v1.Product
	27, // 10: product.v1.GetProductResponse.error:type_name -> product.v1.Error
	0,  // 11: product.v1.GetProductsResponse.products:type_name -> product.v1.Product
	2,  // 12: product.v1.GetProductsResponse.pagination:type_name -> product.v1.Pagination
	27, // 13: product.v1.GetProductsResponse.error:type_name -> product.v1.Error
	0,  // 14: product.v1.UpdateProductResponse.product:type_name -> product.v1.Product
	27, // 15: product.v1.UpdateProductResponse.error:type_name -> product.v1.Error
	0,  // 16: product.v1.UpdateProductStockResponse.product:type_name -> product.v1.Product
	27, // 17: product.v1.UpdateProductStockResponse.error:type_name -> product.v1.Error
	0,  // 18: product.v1.UpdateProductPriceResponse.product:type_name -> product.v1.Product
	27, // 19: product.v1.UpdateProductPriceResponse.error:type_name -> product.v1.Error
	27, // 20: product.v1.DeleteProductResponse.error:type_name -> product.v1.Error
	22, // 21: product.v1.CheckProductAvailabilityResponse.availability:type_name -> product.v1.ProductAvailability
	27, // 22: product.v1.CheckProductAvailabilityResponse.error:type_name -> product.v1.Error
	22, // 23: product.v1.ReserveProductsResponse.reserved_items:type_name -> product.v1.ProductAvailability
	27, // 24: product.v1.ReserveProductsResponse.error:type_name -> product.v1.Error
	27, // 25: product.v1.ConfirmReservationResponse.error:type_name -> product.v1.Error
	27, // 26: product.v1.CancelReservationResponse.error:type_name -> product.v1.Error
	31, // 27: product.v1.Error.details:type_name -> product.v1.Error.DetailsEntry
	4,  // 28: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	5,  // 29: product.v1.ProductService.GetProduct:input_type -> product.v1.GetProductRequest
	6,  // 30: product.v1.ProductService.GetProducts:input_type -> product.v1.GetProductsRequest
	7,  // 31: product.v1.ProductService.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	8,  // 32: product.v1.ProductService.UpdateProductStock:input_type -> product.v1.UpdateProductStockRequest
	9,  // 33: product.v1.ProductService.UpdateProductPrice:input_type -> product.v1.UpdateProductPriceRequest
	10, // 34: product.v1.ProductService.DeleteProduct:input_type -> product.v1.DeleteProductRequest
	11, // 35: product.v1.ProductService.CheckProductAvailability:input_type -> product.v1.CheckProductAvailabilityRequest
	12, // 36: product.v1.ProductService.ReserveProducts:input_type -> product.v1.ReserveProductsRequest
	13, // 37: product.v1.ProductService.ConfirmReservation:input_type -> product.v1.ConfirmReservationRequest
	14, // 38: product.v1.ProductService.CancelReservation:input_type -> product.v1.CancelReservationRequest
	15, // 39: product.v1.ProductService.CreateProduct:output_type -> product.v1.CreateProductResponse
	16, // 40: product.v1.ProductService.GetProduct:output_type -> product.v1.GetProductResponse
	17, // 41: product.v1.ProductService.GetProducts:output_type -> product.v1.GetProductsResponse
	18, // 42: product.v1.ProductService.UpdateProduct:output_type -> product.v1.UpdateProductResponse
	19, // 43: product.v1.ProductService.UpdateProductStock:output_type -> product.v1.UpdateProductStockResponse
	20, // 44: product.v1.ProductService.UpdateProductPrice:output_type -> product.v1.UpdateProductPriceResponse
	21, // 45: product.v1.ProductService.DeleteProduct:output_type -> product.v1.DeleteProductResponse
	23, // 46: product.v1.ProductService.CheckProductAvailability:output_type -> product.v1.CheckProductAvailabilityResponse
	24, // 47: product.v1.ProductService.ReserveProducts:output_type -> product.v1.ReserveProductsResponse
	25, // 48: product.v1.ProductService.ConfirmReservation:output_type -> product.v1.ConfirmReservationResponse
	26, // 49: product.v1.ProductService.CancelReservation:output_type -> product.v1.CancelReservationResponse
	39, // [39:50] is the sub-list for method output_type
	28, // [28:39] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_proto_product_product_proto_init() }
func file_proto_product_product_proto_init() {
	if File_proto_product_product_proto != nil {
		return
	}
	file_proto_product_product_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_product_product_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_product_product_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_product_product_proto_msgTypes[15].OneofWrappers = []any{
		(*CreateProductResponse_Product)(nil),
		(*CreateProductResponse_Error)(nil),
	}
	file_proto_product_product_proto_msgTypes[16].OneofWrappers = []any{
		(*GetProductResponse_Product)(nil),
		(*GetProductResponse_Error)(nil),
	}
	file_proto_product_product_proto_msgTypes[17].OneofWrappers = []any{}
	file_proto_product_product_proto_msgTypes[18].OneofWrappers = []any{
		(*UpdateProductResponse_Product)(nil),
		(*UpdateProductResponse_Error)(nil),
	}
	file_proto_product_product_proto_msgTypes[19].OneofWrappers = []any{
		(*UpdateProductStockResponse_Product)(nil),
		(*UpdateProductStockResponse_Error)(nil),
	}
	file_proto_product_product_proto_msgTypes[20].OneofWrappers = []any{
		(*UpdateProductPriceResponse_Product)(nil),
		(*UpdateProductPriceResponse_Error)(nil),
	}
	file_proto_product_product_proto_msgTypes[21].OneofWrappers = []any{}
	file_proto_product_product_proto_msgTypes[23].OneofWrappers = []any{}
	file_proto_product_product_proto_msgTypes[24].OneofWrappers = []any{}
	file_proto_product_product_proto_msgTypes[25].OneofWrappers = []any{}
	file_proto_product_product_proto_msgTypes[26].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_proto_rawDesc), len(file_proto_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_product_proto_goTypes,
		DependencyIndexes: file_proto_product_product_proto_depIdxs,
		MessageInfos:      file_proto_product_product_proto_msgTypes,
	}.Build()
	File_proto_product_product_proto = out.File
	file_proto_product_product_proto_goTypes = nil
	file_proto_product_product_proto_depIdxs = nil
}
